#!/bin/sh

set -e

echo "Running pre-push hook:"

echo "Executing: cargo clippy --all-targets --workspace -- -D warnings"
cargo clippy --all-targets --workspace -- -D warnings

# echo "Executing: cargo test"
# cargo test
