name: Bug report
description: Found something wrong or broken? If it hasn't already been filed/solved, report it!
labels: ["bug"]
body:
  - type: checkboxes
    id: acknowledgements
    attributes:
      label: Checklist
      options:
        - label: >
            I've looked through the [troubleshooting docs](https://clementtsang.github.io/bottom/nightly/troubleshooting),
            [the known problems list](https://clementtsang.github.io/bottom/nightly/support/official/#known-problems), and 
            [existing open issues](https://github.com/ClementTsang/bottom/issues?q=is%3Aopen+is%3Aissue) for similar
            issues.
          required: true

  - type: input
    id: operating_system
    attributes:
      label: What operating system and version are you using?
      description: >
        Please provide the operating system(s) and version(s) that are experiencing the problem.
        Note that issues on operating systems that [are not officially supported](https://github.com/ClementTsang/bottom#support)
        may not be prioritized/resolved.
      placeholder: Arch Linux 6.6.2

  - type: dropdown
    id: architecture
    attributes:
      label: What architecture are you using?
      description: >
        Please select the architecture(s) that are experiencing the problem.
        Note that systems that [are not officially supported](https://github.com/ClementTsang/bottom#support)
        may not be prioritized/resolved.
      multiple: true
      options:
        - x86_64/AMD64
        - arm64
        - x86
        - arm32
        - Other (please specify in the Additional Information area at the end)

  - type: textarea
    id: terminal
    attributes:
      label: What terminal(s) are you running bottom on that are experiencing the problem?
      description: >
        Please provide what terminal(s) you are running `bottom` on (e.g. Konsole, kitty, urxvt)
        that are experiencing the issue, as well as their version and any relevant settings (e.g. terminal theme).
      placeholder: kitty 0.25.2

  - type: dropdown
    id: filesystem
    validations:
      required: false
    attributes:
      label: (Optional) What filesystem(s) are you using?
      description: >
        If you know, please select what filesystem(s) you are using on the system that is experiencing the problem. This
        can be especially helpful if the issue is related to either the disk or memory widgets.
      multiple: true
      options:
        - ext4
        - NTFS
        - exFAT
        - FAT
        - ZFS
        - Btrfs
        - APFS
        - Other (please specify in the Additional Information area at the end)"

  - type: input
    id: version
    validations:
      required: true
    attributes:
      label: What version of bottom are you running?
      description: >
        Please specify which version of `bottom` you're running that is causing problems. You can find this with
        `btm -V`. If you are using a nightly/non-release version, please also specify that.

        It would also be helpful if you are not running [the latest version](https://github.com/ClementTsang/bottom/releases/latest)
        to try that as well to see if the issue has already been resolved.
      placeholder: 0.11.1

  - type: textarea
    id: install
    validations:
      required: true
    attributes:
      label: How did you install bottom?
      description: >
        Please describe how you installed `bottom`. If you manually compiled it, please also mention your _Rust version_.

        **Note: if you installed `bottom` from cargo, please ensure that you installed the right crate (https://crates.io/crates/bottom).**
      placeholder: Installed bottom through the Arch official repos.

  # TODO: After some point also add in a `btm check` invocation

  - type: textarea
    id: description
    validations:
      required: true
    attributes:
      label: Describe the issue
      description: >
        Give a description of the issue. If possible, provide screenshots/videos.
      placeholder: |
        Example:
        bottom is failing to output information for a mounted encrypted partition on basic mode. It should be able to report this information, but I'm not seeing the entry at all.

  - type: textarea
    id: expected
    validations:
      required: true
    attributes:
      label: What is the expected behaviour?
      description: >
        Describe the behaviour you expected.
      placeholder: |
        Example:
        I expect to be able to see information about the encrypted partition on basic mode.

  - type: textarea
    id: actual
    validations:
      required: true
    attributes:
      label: What is the actual behaviour?
      description: >
        Describe the behaviour you actually see. If possible, provide screenshots/videos.
      placeholder: |
        Example:
        I am unable to see information about my encrypted partition.

  - type: textarea
    id: reproduce
    validations:
      required: true
    attributes:
      label: How can we reproduce this?
      description: >
        Provide detailed steps on _how_ to reproduce your problem, to the best of your ability. Be as detailed as
        possible. Include any config files or flags used. If possible, provide screenshots/videos of the issue.

        Remember - if maintainers cannot reproduce the issue, it will be very hard to fix!
      placeholder: |
        Example:
          1. Mount a LUKS encrypted partition.
          2. Run `btm --basic`
          3. Observe there is no partition shown.

  - type: textarea
    id: additional
    attributes:
      label: Additional information
      description: Provide any additional information you think may be relevant or helpful.
      placeholder: It works fine if I just run it normally without the `--basic` flag.
